maildir: ~/mail
# if omitted (or null), it will use the same as notmuch would, see notmuch-config(1)
notmuch_config: ~/.config/notmuch/notmuchrc

# only rename if you use mbsync
rename: true

# with the `unique` match mode, we can disambiguate files according to a prefix
# of their paths. The prefix is relative to the maildir.
rule_match_mode: unique

# NOTE: rule_match_mode `unique` means that queries must NOT overlap (hence the `and not tag:trash` clause in the second query).
# This is to avoid moving files more than once and checked by notmuch-mailmover *before* any files are moved.
# So, don't worry about it, notmuch-mailmover will complain if your rules are ambiguous.
# However, if a prefix is given, files matching messages in queries are further
# filtred by a prefix of their path, relative to maildir.
# In this example, there are two different directories, `~/mail/mailbox1` and
# `~/mail/mailbox2` representing two different distant accounts. The queries are
# the same, but we disambiguate based on the which subdirectory of `~/mail` the
# files belong to.
rules:
  # move mails tagged as `trash` to folder `mailbox1/Trash` for mailbox1
  - folder: mailbox1/Trash
    query: tag:trash
    prefix: mailbox1

  # move mails tagged as `sent` to folder `mailbox1/Sent` for mailbox1
  - folder: mailbox1/Sent
    query: tag:sent and not tag:trash
    prefix: mailbox1

  # move mails tagged as `archive` to folder `mailbox1/Archive` for mailbox1
  - folder: mailbox1/Archive
    query: tag:archive and not tag:sent and not tag:trash
    prefix: mailbox1

  # move mails tagged as `trash` to folder `mailbox2/Trash` for mailbox2
  - folder: mailbox2/Trash
    query: tag:trash
    prefix: mailbox2

  # move mails tagged as `sent` to folder `mailbox2/Sent` for mailbox2
  - folder: mailbox2/Sent
    query: tag:sent and not tag:trash
    prefix: mailbox2

  # move mails tagged as `archive` to folder `mailbox2/Archive` for mailbox2
  - folder: mailbox2/Archive
    query: tag:archive and not tag:sent and not tag:trash
    prefix: mailbox2


