[package]
name = "notmuch-mailmover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.4.0", features = ["v4"] }
anyhow = "1.0.71"
env_logger = "0.10.0"
log = "0.4.19"
notmuch = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.22"
directories = "5.0.1"
gumdrop = "0.8.1"
shellexpand = "3.0.0"

[dev-dependencies]
regex = "1.8.4"
