.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH notmuch-mailmover 1  "notmuch-mailmover 0.2.0" 
.SH NAME
notmuch\-mailmover
.SH SYNOPSIS
\fBnotmuch\-mailmover\fR [\fB\-c\fR|\fB\-\-config\fR] [\fB\-l\fR|\fB\-\-log\-level\fR] [\fB\-d\fR|\fB\-\-dry\-run\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\fR=\fIFILE\fR
Use the provided config file instead of the default
.TP
\fB\-l\fR, \fB\-\-log\-level\fR=\fILOG_LEVEL\fR [default: info]
Configure the log level
.br

.br
[\fIpossible values: \fRtrace, debug, info, warn, error]
.TP
\fB\-d\fR, \fB\-\-dry\-run\fR
Enable dry\-run mode, i.e. no files are being moved
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.2.0
.SH AUTHORS
Michael Adler <therisen06@gmail.com>
